### PR TITLE
update github action to check simd_backend and add cfg_doc for nightly  

### PR DESCRIPTION
**Pull request by delta1**
Hi @hdevalence, 

This PR adds `feature(doc_cfg)` for the nightly feature and also adds the rustflags env for the github action to test simd_backend ( from the good suggestion in #5 )

I stumbled across an issue when trying to compile with `simd_backend` enabled by running: 

`RUSTFLAGS='-C target-feature=+avx2' cargo +nightly build --features simd_backend` 

The error was: 

```rust
error[E0658]: `#[doc(cfg)]` is experimental
  --> src/backend/vector/mod.rs:21:1
   |
21 | #[doc(cfg(all(target_feature = "avx2", not(target_feature = "avx512ifma"))))]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #43781 <https://github.com/rust-lang/rust/issues/43781> for more information
   = help: add `#![feature(doc_cfg)]` to the crate attributes to enable

error[E0658]: `#[doc(cfg)]` is experimental
  --> src/backend/mod.rs:57:5
   |
57 | /     doc(cfg(any(all(
58 | |         feature = "simd_backend",
59 | |         any(target_feature = "avx2", target_feature = "avx512ifma")
60 | |     ))))
   | |________^
   |
   = note: see issue #43781 <https://github.com/rust-lang/rust/issues/43781> for more information
   = help: add `#![feature(doc_cfg)]` to the crate attributes to enable
``` 

Examples of the github action: 
- failing: https://github.com/delta1/curve25519-dalek-ng/runs/3745497109?check_suite_focus=true 
- passing: https://github.com/delta1/curve25519-dalek-ng/runs/3748344821?check_suite_focus=true

### CODE REVIEW

**Comment by delta1** [comment]
hey @hdevalence hope you are well! Do you have any feedback here please?

**Review by hdevalence — APPROVED** [review]
LGTM, thanks for the reminder :)

**Comment by hdevalence** [comment]
Published `4.1.1` with these changes.

**Comment by delta1** [comment]
Thanks!

**Pull request merged**
